name: build-and-push
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore: [ "**.md" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # needed to push to GHCR
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (amd64 only)
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/pagescms:1.0
          platforms: linux/amd64
          provenance: false

      # If you need ARM64 too, replace the step above with this:
      # - name: Build & push (multi-arch)
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     tags: ghcr.io/${{ github.repository_owner }}/pagescms:1.0
      #     platforms: linux/amd64,linux/arm64
      #     provenance: false
